/* Generated by protobuf-nginx 1.1 - DO NOT EDIT */
extern "C"{
#include <ngx_protobuf.h>
#include "ngx_query_proto.h"
}
/* QueryInfo field descriptors */

ngx_protobuf_field_descriptor_t
ngx_query_info_cleaning_time = {
    ngx_string("cleaning_time"),
    1,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_REQUIRED,
    NGX_PROTOBUF_TYPE_UINT32,
    sizeof(uint32_t),
    0,
    (ngx_protobuf_pack_pt)
    NULL,
    (ngx_protobuf_unpack_pt)
    NULL,
    (ngx_protobuf_size_pt)
    NULL
};

ngx_protobuf_field_descriptor_t
ngx_query_info_remaining_capacity = {
    ngx_string("remaining_capacity"),
    2,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_REQUIRED,
    NGX_PROTOBUF_TYPE_UINT32,
    sizeof(uint32_t),
    0,
    (ngx_protobuf_pack_pt)
    NULL,
    (ngx_protobuf_unpack_pt)
    NULL,
    (ngx_protobuf_size_pt)
    NULL
};

static ngx_protobuf_module_t
ngx_query_proto_module_ctx = {
    NULL
};

ngx_module_t ngx_query_proto_module = {
    NGX_MODULE_V1,
    &ngx_query_proto_module_ctx,
    NULL,
    NGX_PROTOBUF_MODULE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NGX_MODULE_V1_PADDING
};

/* QueryInfo message methods */

ngx_int_t
ngx_query_info__is_initialized(
    ngx_query_info_t *obj)
{
    return (ngx_query_info__has_cleaning_time(obj)
        && ngx_query_info__has_remaining_capacity(obj));
}

ngx_int_t
ngx_query_info__unpack(
    ngx_query_info_t *obj,
    ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
        case 1: /* QueryInfo.cleaning_time */
            if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                if (ngx_protobuf_read_uint32(pos, end,
                    &obj->cleaning_time) != NGX_OK)
                {
                    return NGX_ABORT;
                }
                obj->__has_cleaning_time = 1;
            } else {
                if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                    return NGX_ABORT;
                }
            }
            break;
        case 2: /* QueryInfo.remaining_capacity */
            if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                if (ngx_protobuf_read_uint32(pos, end,
                    &obj->remaining_capacity) != NGX_OK)
                {
                    return NGX_ABORT;
                }
                obj->__has_remaining_capacity = 1;
            } else {
                if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                    return NGX_ABORT;
                }
            }
            break;
        default:
            rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                &obj->__unknown);
            if (rc != NGX_OK) {
                return rc;
            }
            break;
        }
    }

    return NGX_OK;
}

size_t
ngx_query_info__size(
     ngx_query_info_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_cleaning_time) {
        size += ngx_protobuf_size_uint32_field(obj->cleaning_time, 1);
    }
    if (obj->__has_remaining_capacity) {
        size += ngx_protobuf_size_uint32_field(obj->remaining_capacity, 2);
    }

    if (obj->__unknown != NULL
        && obj->__unknown->elts != NULL
        && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

ngx_int_t
ngx_query_info__pack(
    ngx_query_info_t *obj,
    ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_query_info__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_cleaning_time) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
            ctx->buffer.pos,
            obj->cleaning_time,
            1);
    }
    if (obj->__has_remaining_capacity) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
            ctx->buffer.pos,
            obj->remaining_capacity,
            2);
    }

    if (obj->__unknown != NULL
        && obj->__unknown->elts != NULL
        && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

