/* Generated by protobuf-nginx 1.1 - DO NOT EDIT */

#ifndef _NGX_QUERY_PROTO_H_INCLUDED_
#define _NGX_QUERY_PROTO_H_INCLUDED_
extern "C"{
#include <stdint.h>
#include <ngx_config.h>
// #include <ngx_string.h>
// #include <ngx_array.h>
// #include <ngx_palloc.h>
// #include <ngx_rbtree.h>
#include <ngx_protobuf.h>
}

/* QueryInfo */

typedef struct {
    uint32_t     cleaning_time;
    uint32_t     remaining_capacity;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_cleaning_time      : 1;
    uint32_t     __has_remaining_capacity : 1;
} ngx_query_info_t;

/* QueryInfo field methods */

#define ngx_query_info__set_cleaning_time(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, cleaning_time, val)

#define ngx_query_info__clear_cleaning_time(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, cleaning_time)

#define ngx_query_info__has_cleaning_time(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, cleaning_time))

#define ngx_query_info__set_remaining_capacity(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, remaining_capacity, val)

#define ngx_query_info__clear_remaining_capacity(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, remaining_capacity)

#define ngx_query_info__has_remaining_capacity(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, remaining_capacity))

/* QueryInfo message methods */

#define ngx_query_info__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_query_info_t))

#define ngx_query_info__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_query_info_t))

ngx_int_t ngx_query_info__is_initialized(
    ngx_query_info_t *obj);

ngx_int_t ngx_query_info__unpack(
    ngx_query_info_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_query_info__size(
    ngx_query_info_t *obj);

ngx_int_t ngx_query_info__pack(
    ngx_query_info_t *obj,
    ngx_protobuf_context_t *ctx);

#endif /* _NGX_QUERY_PROTO_H_INCLUDED_ */
