/* Generated by protobuf-nginx 1.1 - DO NOT EDIT */

#ifndef _NGX_MAP_PROTO_H_INCLUDED_
#define _NGX_MAP_PROTO_H_INCLUDED_

#include <stdint.h>
#include <ngx_config.h>
//#include <ngx_string.h>
//#include <ngx_array.h>
//#include <ngx_palloc.h>
//#include <ngx_rbtree.h>
#include <ngx_protobuf.h>
//#include "../ngx_empty_proto/ngx_empty_proto.h"

/* MapCell.Value */

typedef enum {
    NGX_MAPCELL_FREE     = 0,
    NGX_MAPCELL_OBSTACLE = 1,
    NGX_MAPCELL_UNKNOWN  = 2
} ngx_map_cell_value_e;

/* MapCell */

typedef struct {
    uint32_t              x;
    uint32_t              y;
    ngx_map_cell_value_e  value;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t          *__unknown;
    uint32_t              __has_x     : 1;
    uint32_t              __has_y     : 1;
    uint32_t              __has_value : 1;
} ngx_map_cell_t;

/* Map */

typedef struct {
    uint32_t     width;
    uint32_t     height;
    /* ngx_map_cell_t */
    ngx_array_t *mapCell;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_width   : 1;
    uint32_t     __has_height  : 1;
    uint32_t     __has_mapCell : 1;
} ngx_map_t;

/* MapCell field methods */

#define ngx_map_cell__set_x(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, x, val)

#define ngx_map_cell__clear_x(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, x)

#define ngx_map_cell__has_x(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, x))

#define ngx_map_cell__set_y(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, y, val)

#define ngx_map_cell__clear_y(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, y)

#define ngx_map_cell__has_y(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, y))

#define ngx_map_cell__set_value(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, value, val)

#define ngx_map_cell__clear_value(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, value)

#define ngx_map_cell__has_value(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, value))

/* MapCell message methods */

#define ngx_map_cell__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_map_cell_t))

#define ngx_map_cell__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_map_cell_t))

ngx_int_t ngx_map_cell__is_initialized(
    ngx_map_cell_t *obj);

ngx_int_t ngx_map_cell__unpack(
    ngx_map_cell_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_map_cell__size(
    ngx_map_cell_t *obj);

ngx_int_t ngx_map_cell__pack(
    ngx_map_cell_t *obj,
    ngx_protobuf_context_t *ctx);

/* Map field methods */

#define ngx_map__set_width(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, width, val)

#define ngx_map__clear_width(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, width)

#define ngx_map__has_width(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, width))

#define ngx_map__set_height(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, height, val)

#define ngx_map__clear_height(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, height)

#define ngx_map__has_height(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, height))

#define ngx_map__set_mapCell(obj, val) \
    NGX_PROTOBUF_SET_MEMBER(obj, mapCell, val)

ngx_map_cell_t *
ngx_map__add__mapCell(
    ngx_map_t *obj,
    ngx_pool_t *pool);

#define ngx_map__clear_mapCell(obj) \
    NGX_PROTOBUF_CLEAR_MEMBER(obj, mapCell)

#define ngx_map__has_mapCell(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, mapCell) && \
     (obj)->mapCell->nelts > 0)

/* Map message methods */

#define ngx_map__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_map_t))

#define ngx_map__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_map_t))

ngx_int_t ngx_map__is_initialized(
    ngx_map_t *obj);

ngx_int_t ngx_map__unpack(
    ngx_map_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_map__size(
    ngx_map_t *obj);

ngx_int_t ngx_map__pack(
    ngx_map_t *obj,
    ngx_protobuf_context_t *ctx);

#endif /* _NGX_MAP_PROTO_H_INCLUDED_ */
