/* Generated by protobuf-nginx 1.1 - DO NOT EDIT */
extern "C"{
#include <ngx_protobuf.h>
#include "ngx_control_proto.h"
}
/* ControlCode field descriptors */

ngx_protobuf_field_descriptor_t
ngx_control_code_opt_code = {
    ngx_string("opt_code"),
    1,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_REQUIRED,
    NGX_PROTOBUF_TYPE_UINT32,
    sizeof(uint32_t),
    0,
    (ngx_protobuf_pack_pt)
    NULL,
    (ngx_protobuf_unpack_pt)
    NULL,
    (ngx_protobuf_size_pt)
    NULL
};

/* ErrorCode field descriptors */

ngx_protobuf_field_descriptor_t
ngx_error_code_error_code = {
    ngx_string("error_code"),
    1,
    NGX_PROTOBUF_WIRETYPE_VARINT,
    NGX_PROTOBUF_LABEL_REQUIRED,
    NGX_PROTOBUF_TYPE_UINT32,
    sizeof(uint32_t),
    0,
    (ngx_protobuf_pack_pt)
    NULL,
    (ngx_protobuf_unpack_pt)
    NULL,
    (ngx_protobuf_size_pt)
    NULL
};

static ngx_protobuf_module_t
ngx_control_proto_module_ctx = {
    NULL
};

ngx_module_t ngx_control_proto_module = {
    NGX_MODULE_V1,
    &ngx_control_proto_module_ctx,
    NULL,
    NGX_PROTOBUF_MODULE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NGX_MODULE_V1_PADDING
};

/* ControlCode message methods */

ngx_int_t
ngx_control_code__is_initialized(
    ngx_control_code_t *obj)
{
    return (ngx_control_code__has_opt_code(obj));
}

ngx_int_t
ngx_control_code__unpack(
    ngx_control_code_t *obj,
    ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
        case 1: /* ControlCode.opt_code */
            if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                if (ngx_protobuf_read_uint32(pos, end,
                    &obj->opt_code) != NGX_OK)
                {
                    return NGX_ABORT;
                }
                obj->__has_opt_code = 1;
            } else {
                if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                    return NGX_ABORT;
                }
            }
            break;
        default:
            rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                &obj->__unknown);
            if (rc != NGX_OK) {
                return rc;
            }
            break;
        }
    }

    return NGX_OK;
}

size_t
ngx_control_code__size(
     ngx_control_code_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_opt_code) {
        size += ngx_protobuf_size_uint32_field(obj->opt_code, 1);
    }

    if (obj->__unknown != NULL
        && obj->__unknown->elts != NULL
        && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

ngx_int_t
ngx_control_code__pack(
    ngx_control_code_t *obj,
    ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_control_code__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_opt_code) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
            ctx->buffer.pos,
            obj->opt_code,
            1);
    }

    if (obj->__unknown != NULL
        && obj->__unknown->elts != NULL
        && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

/* ErrorCode message methods */

ngx_int_t
ngx_error_code__is_initialized(
    ngx_error_code_t *obj)
{
    return (ngx_error_code__has_error_code(obj));
}

ngx_int_t
ngx_error_code__unpack(
    ngx_error_code_t *obj,
    ngx_protobuf_context_t *ctx)
{
    u_char      **pos = &ctx->buffer.pos;
    u_char       *end = ctx->buffer.last;
    uint32_t      header;
    uint32_t      field;
    uint32_t      wire;
    ngx_int_t     rc;

    while (*pos < end) {
        if (ngx_protobuf_read_uint32(pos, end, &header) != NGX_OK) {
            return NGX_ABORT;
        }

        if (*pos >= end) {
            return NGX_ABORT;
        }

        field = header >> 3;
        wire = header & 0x07;

        switch (field) {
        case 1: /* ErrorCode.error_code */
            if (wire == NGX_PROTOBUF_WIRETYPE_VARINT) {
                if (ngx_protobuf_read_uint32(pos, end,
                    &obj->error_code) != NGX_OK)
                {
                    return NGX_ABORT;
                }
                obj->__has_error_code = 1;
            } else {
                if (ngx_protobuf_skip(pos, end, wire) != NGX_OK) {
                    return NGX_ABORT;
                }
            }
            break;
        default:
            rc = ngx_protobuf_unpack_unknown_field(field, wire, ctx,
                &obj->__unknown);
            if (rc != NGX_OK) {
                return rc;
            }
            break;
        }
    }

    return NGX_OK;
}

size_t
ngx_error_code__size(
     ngx_error_code_t *obj)
{
    size_t      size = 0;
    ngx_uint_t  i;

    if (obj->__has_error_code) {
        size += ngx_protobuf_size_uint32_field(obj->error_code, 1);
    }

    if (obj->__unknown != NULL
        && obj->__unknown->elts != NULL
        && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t *unk = obj->__unknown->elts;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            size += ngx_protobuf_size_unknown_field(unk + i);
        }
    }

    return size;
}

ngx_int_t
ngx_error_code__pack(
    ngx_error_code_t *obj,
    ngx_protobuf_context_t *ctx)
{
    size_t     size = ngx_error_code__size(obj);
    ngx_int_t  rc;

    if (size == 0) {
        return NGX_OK;
    }

    if (ctx->buffer.pos + size > ctx->buffer.last) {
        return NGX_ABORT;
    }

    if (obj->__has_error_code) {
        ctx->buffer.pos = ngx_protobuf_write_uint32_field(
            ctx->buffer.pos,
            obj->error_code,
            1);
    }

    if (obj->__unknown != NULL
        && obj->__unknown->elts != NULL
        && obj->__unknown->nelts > 0)
    {
        ngx_protobuf_unknown_field_t  *unk = obj->__unknown->elts;
        ngx_uint_t                     i;

        for (i = 0; i < obj->__unknown->nelts; ++i) {
            rc = ngx_protobuf_pack_unknown_field(unk + i, ctx);
            if (rc != NGX_OK) {
                return rc;
            }
        }
    }

    return NGX_OK;
}

