/* Generated by protobuf-nginx 1.1 - DO NOT EDIT */

#ifndef _NGX_POSE_PROTO_H_INCLUDED_
#define _NGX_POSE_PROTO_H_INCLUDED_

#include <stdint.h>
#include <ngx_config.h>
// #include <ngx_string.h>
// #include <ngx_array.h>
// #include <ngx_palloc.h>
// #include <ngx_rbtree.h>
#include <ngx_protobuf.h>

/* Empty */

typedef struct {
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
} ngx_empty_t;

/* Pose */

typedef struct {
    uint32_t     x;
    uint32_t     y;
    /* ngx_protobuf_unknown_field_t */
    ngx_array_t *__unknown;
    uint32_t     __has_x : 1;
    uint32_t     __has_y : 1;
} ngx_pose_t;

/* Empty field methods */

/* Empty message methods */

#define ngx_empty__alloc(pool) \
    ngx_pcalloc(pool, \
    sizeof(ngx_empty_t))

#define ngx_empty__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_empty_t))

ngx_int_t ngx_empty__is_initialized(
    ngx_empty_t *obj);

ngx_int_t ngx_empty__unpack(
    ngx_empty_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_empty__size(
    ngx_empty_t *obj);

ngx_int_t ngx_empty__pack(
    ngx_empty_t *obj,
    ngx_protobuf_context_t *ctx);

/* Pose field methods */

#define ngx_pose__set_x(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, x, val)

#define ngx_pose__clear_x(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, x)

#define ngx_pose__has_x(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, x))

#define ngx_pose__set_y(obj, val) \
    NGX_PROTOBUF_SET_NUMBER(obj, y, val)

#define ngx_pose__clear_y(obj) \
    NGX_PROTOBUF_CLEAR_NUMBER(obj, y)

#define ngx_pose__has_y(obj) \
    (NGX_PROTOBUF_HAS_FIELD(obj, y))

/* Pose message methods */

#define ngx_pose__alloc(pool) \
    ngx_pcalloc( pool, \
    sizeof(ngx_pose_t))

#define ngx_pose__clear(obj) \
    ngx_memzero(obj, sizeof(ngx_pose_t))

ngx_int_t ngx_pose__is_initialized(
    ngx_pose_t *obj);

ngx_int_t ngx_pose__unpack(
    ngx_pose_t *obj,
    ngx_protobuf_context_t *ctx);

size_t ngx_pose__size(
    ngx_pose_t *obj);

ngx_int_t ngx_pose__pack(
    ngx_pose_t *obj,
    ngx_protobuf_context_t *ctx);

#endif /* _NGX_POSE_PROTO_H_INCLUDED_ */
